module.exports = async function ({ page, t }) {
  const w = page("Index.html");
  const D = w.Donnees;
  const c = D.ajouterClient({ nom: "Castelmoron", ville: "castelmoron-sur-lot", codePostal: "47260", debutCampagne: 1, finCampagne: 12, notes: "Accès quai 2" });
  const l1 = D.enregistrerLigne(c.id, { nom: "Ligne 2", formatHabituel: "1/2H" });
  const l2 = D.enregistrerLigne(c.id, { nom: "Ligne 9" });
  D.definirStatutLigne(l2.id, "inactive");
  D.enregistrerContact(c.id, { role: "Responsable sertissage", prenom: "Benoit", nom: "Deffieux", mobile: "06.26.34.33.70", principal: true });
  D.enregistrerRdv({ clientId: c.id, date: D.ajouterJours(D.aujourdhuiIso(), 2), type: "homologation", ligneIds: [l1.id] });
  D.enregistrerVisite({ ligneId: l1.id, date: "2026-01-10", type: "essai", remarques: "essai molettes" });
  const wd = page("Index.html", w.localStorage.getItem("acsc_donnees_v1"));
  const carte = wd.document.querySelector("[data-apercu-client]");
  t("carte « À visiter » : cliquable (rôle bouton)", carte && carte.getAttribute("role") === "button" && carte.getAttribute("tabindex") === "0");
  t("carte : le nom n'est plus un lien qui quitte la page", !carte.querySelector("a.carte-a-visiter-nom"));
  carte.querySelector(".ligne-echeance-texte").click();
  const f = wd.document.querySelector(".feuille");
  t("clic sur la carte : fenêtre ouverte (centrée sur PC)", !f.hidden && f.classList.contains("feuille--bas") && f.querySelector(".feuille-titre").textContent.includes("Castelmoron"));
  t("fiche rapide : contact et téléphone", f.textContent.includes("Benoit Deffieux") && !!f.querySelector('a[href="tel:06.26.34.33.70"]'));
  t("fiche rapide : RDV en couleur et cliquable", f.textContent.includes("Homologation") && !!f.querySelector("[data-rdv-ouvrir]"));
  t("fiche rapide : lignes actives seulement", f.textContent.includes("Ligne 2") && !f.textContent.includes("Ligne 9"));
  t("fiche rapide : état de la ligne", f.textContent.includes("Pas encore vue"));
  t("fiche rapide : dernières visites", f.textContent.includes("10/01/2026") && f.textContent.includes("essai molettes"));
  t("fiche rapide : notes du client", f.textContent.includes("Accès quai 2"));
  t("fiche rapide : lien vers la fiche complète", !!f.querySelector('a[href="Client.html?id=' + encodeURIComponent(c.id) + '"]'));
  f.querySelector("[data-apercu-visite]").click();
  t("« Visite faite » depuis la fiche rapide : saisie de la bonne ligne", !!wd.document.getElementById("form-visite") && wd.document.getElementById("fv-ligne").value === l1.id);
  wd.AppLayout.fermerFeuille();
  carte.querySelector(".ligne-echeance-texte").click();
  wd.document.querySelector(".feuille [data-apercu-planifier]").click();
  t("« Planifier » depuis la fiche rapide : client pré-choisi", !!wd.document.getElementById("form-rdv") && wd.document.getElementById("fr-client").value === c.id);
  wd.AppLayout.fermerFeuille();
  carte.querySelector("[data-visite]").click();
  t("bouton « Visite faite » de la carte : garde son action (pas la fiche)", !!wd.document.getElementById("form-visite"));
  wd.AppLayout.fermerFeuille();
  carte.querySelector("[data-rdv-pastille]").click();
  t("pastille RDV de la carte : détail du RDV", !!wd.document.querySelector(".feuille [data-rdv-modifier]") && !wd.document.querySelector(".feuille [data-apercu-planifier]"));
  wd.AppLayout.fermerFeuille();
  carte.dispatchEvent(new wd.KeyboardEvent("keydown", { key: "Enter" }));
  t("clavier : Entrée ouvre la fiche rapide", !!wd.document.querySelector(".feuille [data-apercu-planifier]"));
};
